from xeger import Xeger
import rstr
import time
import keyboard
import os
from datetime import datetime
from numba import jit, cuda
import numpy as np


def menu():
    print()
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    print("HH-----------------------------------------------------------HH")
    print("HH----HHH---HHH---PPPPPPPPP----III---LLL---------OOOOOO------HH")
    print("HH----HHH---HHH---PPP----PPP---III---LLL-------OOO----OOO----HH")
    print("HH----HHH---HHH---PPP----PP----III---LLL------OOO------OOO---HH")
    print("HH----HHHHHHHHH---PPPPPPP------III---LLL------OOO------OOO---HH")
    print("HH----HHH---HHH---PPP----------III---LLL------OOO------OOO---HH")
    print("HH----HHH---HHH---PPP----------III---LLLLLLLLL-OOO----OOO----HH")
    print("HH----HHH---HHH---PPP----------III---LLLLLLLLL---OOOOOO------HH")
    print("HH-----------------------------------------------------------HH")
    print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHhHH")
    time.sleep(2)
    print(' loading.', end='\r')
    time.sleep(1)
    print(' loading..', end='\r')
    time.sleep(1)
    print(' loading...', end='\r')
    time.sleep(1)

    print(' loading....', end='\r')
    time.sleep(1)
    print(' loading.', end='\r')
    time.sleep(1)
    print(' loading..', end='\r')
    time.sleep(1)
    print(' loading...', end='\r')
    time.sleep(0.5)
    print(' loading....', end='\r')
    time.sleep(0.4)
    print(' loading.....', end='\r')
    time.sleep(0.3)
    print(' loading......', end='\r')
    time.sleep(0.2)
    print(' loading.......', end='\r')
    time.sleep(0.1)
    print(' loading........', end='\r')
    print(" NOTE: Your master password list will be automatically saved\n in the same directory from where you run this program.")
    print("----------------------------------------------------------")
    time.sleep(3)
    print(" Click anywhere at any time to PAUSE")
    time.sleep(2)
    print(" Press anykey at anytime to RESUME")
    time.sleep(2)
    print(" Press <CTRL> + C to STOP the program")
    time.sleep(0.3)
    print(' ☻', end='\r')
    time.sleep(0.8)
    print(' ☻☺', end='\r')
    time.sleep(0.7)
    print(' ☻☺☻', end='\r')
    time.sleep(0.6)
    print(' ☻☺☻☺', end='\r')
    time.sleep(0.5)
    print(' ☻☺☻☺☻', end='\r')
    time.sleep(0.4)
    print(' ☻☺☻☺☻☺', end='\r')
    time.sleep(0.3)
    print(' ☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.2)
    print(' ☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻', end='\r')
    time.sleep(0.1)
    print(' ☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺☻☺', end='\r')
    print()
    print(" Press ENTER to generate HP ILO passwords: ", end='')
    input('<ENTER>')
    print("=========================================")
    print(" % Complete       # of Passwords     File Size    ETA")
    File_object = open("masterlist.txt","w")
    start_time = time.time()
    x = 1

    while x < 2900000000:
        pwd = (rstr.xeger(r'^([A-Z0-9]{8})((?!AAA|BBB|CCC|DDD|EEE|FFF|GGG|HHH|III|JJJ|KKK|LLL|MMM|NNN|OOO|PPP|QQQ|RRR|SSS|TTT|UUU|VVV|WWW|XXX|YYY|ZZZ|AAAA|BBBB|CCCC|DDDD|EEEE|FFFF|GGGG|HHHH|IIII|JJJJ|KKKK|LLLL|MMMM|NNNN|OOOO|PPPP|QQQQ|RRRR|SSSS|TTTT|UUUU|VVVV|WWWW|XXXX|YYYY|ZZZZ|AAAAA|BBBBB|CCCCC|DDDDD|EEEEE|FFFFF|GGGGG|HHHHH|IIIII|JJJJJ|KKKKK|LLLLL|MMMMM|NNNNN|OOOOO|PPPPP|QQQQQ|RRRRR|SSSSS|TTTTT|UUUUU|VVVVV|WWWWW|XXXXX|YYYYY|ZZZZZ|AAAAAAA|BBBBBB|CCCCCC|DDDDDD|EEEEEE|FFFFFF|GGGGGG|HHHHHH|IIIIII|JJJJJJ|KKKKKK|LLLLLL|MMMMMM|NNNNNN|OOOOOO|PPPPPP|QQQQQQ|RRRRRR|SSSSSS|TTTTTT|UUUUUU|VVVVVV|WWWWWW|XXXXXX|YYYYYY|ZZZZZZ|AAAAAAA|BBBBBBB|CCCCCCC|DDDDDDD|EEEEEEE|FFFFFFF|GGGGGGG|HHHHHHH|IIIIIII|JJJJJJJ|KKKKKKK|LLLLLLL|MMMMMMM|NNNNNNN|OOOOOOO|PPPPPPP|QQQQQQQ|RRRRRRR|SSSSSSS|TTTTTTT|UUUUUUU|VVVVVVV|WWWWWWW|XXXXXXX|YYYYYYY|ZZZZZZZ|AAAAAAAA|BBBBBBBB|CCCCCCCC|DDDDDDDD|EEEEEEEE|FFFFFFFF|GGGGGGGG|HHHHHHHH|IIIIIIII|JJJJJJJJ|KKKKKKKK|LLLLLLLL|MMMMMMMM|NNNNNNNN|OOOOOOOO|PPPPPPPP|QQQQQQQQ|RRRRRRRR|SSSSSSSS|TTTTTTTT|UUUUUUUU|VVVVVVVV|WWWWWWWW|XXXXXXXX|YYYYYYYY|ZZZZZZZZ|ABC|BCD|CDE|DEF|EFG|FGH|GHI|HIJ|IJK|JKL|KLM|LMN|MNO|NOP|OPQ|PQR|QRS|RST|STU|TUV|UVW|VWX|WXY|XZY|a|b|c|d|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|aa|bb|cc|dd|ee|ff|gg|hh|ii|jj|kk|ll|mm|nn|oo|pp|qq|rr|ss|tt|uu|vv|ww|xx|yy|zz|aaa|bbb|ccc|ddd|eee|fff|ggg|hhh|iii|jjj|kkk|lll|mmm|nnn|ooo|ppp|qqq|rrr|sss|ttt|uuu|vvv|www|xxx|yyy|zzz|aaaa|bbbb|cccc|dddd|eeee|ffff|gggg|hhhh|iiii|jjjj|kkkk|llll|mmmm|nnnn|oooo|pppp|qqqq|rrrr|ssss|tttt|uuuu|vvvv|wwww|xxxx|yyyy|zzzz|aaaaa|bbbbb|ccccc|ddddd|eeeee|fffff|ggggg|hhhhh|iiiii|jjjjj|kkkkk|lllll|mmmmm|nnnnn|ooooo|ppppp|qqqqq|rrrrr|sssss|ttttt|uuuuu|vvvvv|wwwww|xxxxx|yyyyy|zzzzz|aaaaaaa|bbbbbb|cccccc|dddddd|eeeeee|ffffff|gggggg|hhhhhh|iiiiii|jjjjjj|kkkkkk|llllll|mmmmmm|nnnnnn|oooooo|pppppp|qqqqqq|rrrrrr|ssssss|tttttt|uuuuuu|vvvvvv|wwwwww|xxxxxx|yyyyyy|zzzzzz|aaaaaaa|bbbbbbb|ccccccc|ddddddd|eeeeeee|fffffff|ggggggg|hhhhhhh|iiiiiii|jjjjjjj|kkkkkkk|lllllll|mmmmmmm|nnnnnnn|ooooooo|ppppppp|qqqqqqq|rrrrrrr|sssssss|ttttttt|uuuuuuu|vvvvvvv|wwwwwww|xxxxxxx|yyyyyyy|zzzzzzz|aaaaaaaa|bbbbbbbb|cccccccc|dddddddd|eeeeeeee|ffffffff|gggggggg|hhhhhhhh|iiiiiiii|jjjjjjjj|kkkkkkkk|llllllll|mmmmmmmm|nnnnnnnn|oooooooo|pppppppp|qqqqqqqq|rrrrrrrr|ssssssss|tttttttt|uuuuuuuu|vvvvvvvv|wwwwwwww|xxxxxxxx|yyyyyyyy|zzzzzzzz|abc|bcd|cde|def|efg|fgh|ghi|hij|ijk|jkl|klm|lmn|mno|nop|opq|pqr|qrs|rst|stu|tuv|uvw|vwx|wxy|xzy|000|111|222|333|444|555|666|777|888|999|012|123|234|345|456|567|678|789|000|111|222|333|444|555|666|777|888|999|0000|1111|2222|3333|4444|5555|6666|7777|8888|9999|00000|11111|22222|33333|44444|55555|66666|77777|88888|99999|000000|111111|222222|333333|444444|555555|666666|777777|888888|999999|0000000|1111111|2222222|3333333|4444444|5555555|6666666|7777777|8888888|9999999|00000000|11111111|22222222|33333333|44444444|55555555|66666666|77777777|88888888|99999999))$'))
        File_object.write(pwd)
        File_object.write("\n")
        file_size = os.path.getsize("masterlist.txt")
        megabytes = file_size / 1000000
        elapsed_time = time.time() - start_time
        elapsed_time_seconds = elapsed_time
        maxpass = 2900000000
        x += 1
        y = x
        y = (100 * float(x) / float(2900000000.0))
        passwords_per_second = x / elapsed_time_seconds
        timeleft = maxpass / passwords_per_second
        timeleft_days = timeleft / 86400
        timeleft_days_formatted = timeleft_days
        mbstr = (megabytes)
        print("%6.3f"%(float(y))+" Complete   "+str(x)+" Passwords   "+"%6.3f"%(megabytes)+' MB   '+"%3.3f"%(timeleft_days_formatted)+" Days", end='\r')


now = datetime.now()
now_time = now.strftime("%H%M")
menu()
